// Generated by CoffeeScript 1.6.1
(function() {
  var Enemy;

  Enemy = (function() {

    function Enemy() {
      this.position = {
        x: 400,
        y: 460
      };
      this.speed = 4;
      this.angle = 0;
      this.rotation = 0;
      this.target = null;
      this.waypoints = [];
      this.size = 24;
    }

    Enemy.prototype.update = function() {
      var row, tile, _i, _j, _len, _len1, _ref;
      _ref = game.level.tiles;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        for (_j = 0, _len1 = row.length; _j < _len1; _j++) {
          tile = row[_j];
          tile.fill = null;
        }
      }
      return game.level.findIntersection(this.position.x, this.position.y, game.player.position.x, game.player.position.y);
    };

    Enemy.prototype.render = function() {
      game.context.beginPath();
      game.context.fillStyle = "#ff99ee";
      game.context.translate(this.size * 0.5, this.size * 0.5);
      game.context.rotate(-this.rotation);
      game.context.translate(-this.position.x, -this.position.y);
      game.context.rect(0, 0, this.size, this.size);
      game.context.resetTransform();
      return game.context.fill();
    };

    return Enemy;

  })();

  window.Enemy = Enemy;

}).call(this);
