// Generated by CoffeeScript 1.6.1
(function() {
  var Enemy;

  Enemy = (function() {

    function Enemy(x, y) {
      this.position = {
        x: x || 400,
        y: y || 460
      };
      this.speed = 4;
      this.angle = 0;
      this.rotation = 0;
      this.target = null;
      this.waypoints = [];
      this.size = 24;
      this.color = "#ff99ee";
    }

    Enemy.prototype.update = function() {
      if (game.level.findIntersection(this.position.x, this.position.y, game.player.position.x, game.player.position.y)) {
        return this.color = "#0099ff";
      } else {
        return this.color = "#ff99ee";
      }
    };

    Enemy.prototype.render = function() {
      game.context.beginPath();
      game.context.fillStyle = this.color;
      game.context.translate(this.size * 0.5, this.size * 0.5);
      game.context.rotate(-this.rotation);
      game.context.translate(-this.position.x, -this.position.y);
      game.context.rect(0, 0, this.size, this.size);
      game.context.resetTransform();
      return game.context.fill();
    };

    return Enemy;

  })();

  window.Enemy = Enemy;

}).call(this);
