// Generated by CoffeeScript 1.6.1
(function() {
  var KeyHandler;

  KeyHandler = (function() {
    var KEY_MAP;

    function KeyHandler() {}

    KeyHandler.KEY_MAP = KEY_MAP = {
      'up': 38,
      'down': 40,
      'left': 37,
      'right': 39,
      'space': 32,
      'enter': 13,
      'escape': 27,
      'e': 69,
      'w': 87,
      'a': 65,
      'd': 68,
      's': 83
    };

    KeyHandler.listen = function() {
      var _this = this;
      if (this.downListener) {
        return;
      }
      this.pressed = {};
      this.mouse = {};
      this.downListener = window.addEventListener('keydown', function(e) {
        _this.pressed[e.keyCode] = true;
        return e.stopPropagation();
      });
      this.upListener = window.addEventListener('keyup', function(e) {
        _this.pressed[e.keyCode] = false;
        return e.stopPropagation();
      });
      window.addEventListener('mousemove', function(e) {
        _this.mouse.x = e.x;
        _this.mouse.y = e.y;
        return e.stopPropagation();
      });
      window.addEventListener('mousedown', function(e) {
        _this.mousePressed = true;
        return e.stopPropagation();
      });
      return window.addEventListener('mouseup', function(e) {
        _this.mousePressed = false;
        return e.stopPropagation();
      });
    };

    KeyHandler.isDown = function(keyName) {
      return this.pressed[KEY_MAP[keyName]];
    };

    return KeyHandler;

  })();

  window.KeyHandler = KeyHandler;

}).call(this);
