// Generated by CoffeeScript 1.6.1
(function() {
  var Game,
    _this = this;

  Game = (function() {

    function Game(canvas) {
      var _this = this;
      this.canvas = canvas;
      this.render = function() {
        return Game.prototype.render.apply(_this, arguments);
      };
      this.context = this.canvas.getContext('2d');
      this.width = this.canvas.width;
      this.height = this.canvas.height;
    }

    Game.prototype.render = function() {
      return requestAnimationFrame(this.render, this.canvas);
    };

    return Game;

  })();

  window.game = new Game(document.getElementById('game'));

  game.render();

}).call(this);
