// Generated by CoffeeScript 1.6.1
(function() {
  var Player;

  Player = (function() {

    function Player() {
      this.position = {
        x: 0,
        y: 0
      };
      this.tile = {
        row: 0,
        col: 0
      };
      this.speed = 5;
      this.angle = 0;
      this.size = 32;
    }

    Player.prototype.update = function() {
      var dx, dy;
      if (KeyHandler.isDown('w')) {
        this.position.y -= this.speed;
      }
      if (KeyHandler.isDown('s')) {
        this.position.y += this.speed;
      }
      if (KeyHandler.isDown('a')) {
        this.position.x -= this.speed;
      }
      if (KeyHandler.isDown('d')) {
        this.position.x += this.speed;
      }
      dx = KeyHandler.mouse.x - this.position.x;
      dy = KeyHandler.mouse.y - this.position.y;
      this.angle = Math.atan2(dy, dx);
      this.tile.row = Math.floor(this.position.y / Tile.size);
      return this.tile.col = Math.floor(this.position.x / Tile.size);
    };

    Player.prototype.render = function() {
      game.context.beginPath();
      game.context.fillStyle = "#ff9900";
      game.context.translate(this.size * 0.5, this.size * 0.5);
      game.context.rotate(-this.angle);
      game.context.translate(-this.position.x, -this.position.y);
      game.context.rect(0, 0, this.size, this.size);
      game.context.resetTransform();
      return game.context.fill();
    };

    return Player;

  })();

  window.Player = Player;

}).call(this);
