// Generated by CoffeeScript 1.6.1
(function() {
  var Tile;

  Tile = (function() {

    function Tile(params) {
      this.type = params.type || '.';
      this.row = params.row;
      this.col = params.col;
      this.width = 128;
      this.height = 128;
      this.image = document.createElement('img');
      this.image.src = (function() {
        switch (this.type) {
          case '.':
            return 'img/wood.png';
          case 'x':
            return 'img/rock.png';
        }
      }).call(this);
    }

    Tile.prototype.render = function() {
      game.context.fillStyle = '#ff9900';
      game.context.drawImage(this.image, this.col * this.width, this.row * this.height);
      return game.context.fill();
    };

    return Tile;

  })();

  window.Tile = Tile;

}).call(this);
