// Generated by CoffeeScript 1.6.1
(function() {
  var Tile;

  Tile = (function() {

    function Tile(params) {
      this.type = params.type || '.';
      this.row = params.row;
      this.col = params.col;
      this.image = document.createElement('img');
      this.image.src = (function() {
        switch (this.type) {
          case '.':
            return 'img/wood.png';
          case 'x':
            return 'img/rock.png';
        }
      }).call(this);
    }

    Tile.prototype.render = function() {
      return game.context.drawImage(this.image, this.col * Tile.size, this.row * Tile.size);
    };

    return Tile;

  })();

  Tile.size = 64;

  window.Tile = Tile;

}).call(this);
