// Generated by CoffeeScript 1.6.1
(function() {
  var Vector;

  Vector = (function() {

    function Vector(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    }

    Vector.prototype.magnitude = function() {
      return Math.sqrt(this.x * this.x + this.y * this.y);
    };

    Vector.prototype.normalize = function() {
      var magnitude;
      magnitude = this.magnitude();
      this.x /= magnitude;
      return this.y /= magnitude;
    };

    Vector.prototype.dot = function(vec) {
      return this.x * vec.x + this.y * vec.y;
    };

    Vector.prototype.copy = function() {
      return new Vector(this.x, this.y);
    };

    Vector.prototype.angleBetween = function(vec) {
      var angle, vec1, vec2;
      vec1 = this.copy();
      vec2 = vec.copy();
      vec1.normalize();
      vec2.normalize();
      angle = Math.acos(vec1.dot(vec2));
      return angle * 180 / Math.PI;
    };

    return Vector;

  })();

  window.Vector = Vector;

}).call(this);
